### ISSUE TITLE
Differences between new and old versions of dataset and predictions

### ISSUE THREAD

**Issue by mgarort** [sohviluukkonen/kinase-modelling#3]
Hello,

A couple of weeks ago I downloaded the dataset and predictions (not sure if from this repository or from https://github.com/CDDLeiden/kinase-modelling , are they the same? ). Somehow, the dataset I downloaded is no longer the same dataset that appears in the repo; it seems that the splits and the predictions have changed. I am not sure if I downloaded the wrong version or if the repo has been pushed to and updated in the last few weeks. But I was doing some experiments and am a bit confused by the two versions. Do you think you could explain the differences between the new and old dataset and predictions?

- Dataset: how do the old and new splits differ from each other? The results in the paper correspond to which version?
- Predictions: were the new predictions made by the exact same models as before, or were the models re-trained when the dataset split was updated? (I assume the latter, but just to be sure.) Also, the results in the paper correspond to which version?

In particular, I am only using the scaffold split DGBC.

Thanks a lot!

**Comment by sohviluukkonen** [comment]
Hi @mgarort, 

The initial datasets (and thus splits, models, and predictions, a693f7fb80b8bc34bdd4efee9ec5059ab5078167) correspond to the results presented in our [preprint](https://chemrxiv.org/engage/chemrxiv/article-details/63d29b391fb2a8b6fae1da11). 

During the review process, we updated the preprocessing of the dataset to remove allosteric compounds, which led to new datasets, splits, models, and predictions. The results presented in the [paper](https://doi.org/10.1021/acs.jcim.3c00132), correspond to current version of both repos (16d34678a27e00a0806872c8cbbd91ff74ed1a97)

You probably initially downloaded the datasets and predictions from the https://github.com/CDDLeiden/kinase-modelling fork of this repo which I had forgotten to sync with the updates from this repo. Sorry for that, now both of the repos correspond to the published version.

**Comment by mgarort** [comment]
Hi @sohviluukkonen , thank you very much for your detailed answer. That clarifies my questions. I will close the issue now.
